name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0     # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.2'
          # extended: true

      - uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'JenkinsDev'
          repository: 'obsidian'
          access-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Transform Notes
        run: |
          pip install obsidian_to_hugo
          rm -rf ./obsidian/Private
          mv ./obsidian/Public/* .
          rm -rf ./obsidian/Public
          mkdir ./content/notes
          python -m obsidian_to_hugo --obsidian-vault-dir ./obsidian/ --hugo-content-dir ./content/notes

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public


