name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0     # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.121.2'
          # extended: true

      - uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'JenkinsDev'
          repository: 'obsidian'
          access-token: ${{ secrets.ACCESS_TOKEN }}

      - name: Build w/ Notes
        run: |
          curl -Lo obsidian-for-hugo.tar.gz https://github.com/JenkinsDev/obsidian-for-hugo/releases/download/0.1.2/obsidian-for-hugo-0.1.2-linux-amd64.tar.gz
          tar -xf ./obsidian-for-hugo.tar.gz
          mkdir ./content/notes
          ./obsidian-for-hugo -vault-path ./obsidian/Public -content-path ./content/notes
          hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
